### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by tdealtry**
I just noticed that the travis build was doing stuff that would only work with the Dockerfile updates we made last week. This should fix that
Why it was reporting success, I don't know...

### CODE REVIEW

**Comment by tdealtry** [comment]
Hmm something still not working. Still takes 0.72 s to run the "script" line, which should take at least a minute (it's recompiling WCSim, and compiling TriggerApplication). Any ideas?

**Comment by brichards64** [comment]
iv attached stdout and stderr, so we can see whats going on inside the docker container during the build

**Comment by brichards64** [comment]
well nice to know something breaks it even if its just me getting the options in the wrong order

**Comment by brichards64** [comment]
they seem to ahve changed the default command appending which is very strange and i dont understand it as the documentation says its still there but its clearly not working. Also i had to change the " to ' so that $WCSIMDIR isnt evaluated in the host.

**Pull request merged**
