### PR TITLE
Add SN direction tool

### PR DESCRIPTION
**Pull request by ast0815**

### CODE REVIEW

**Comment by tdealtry** [comment]
Great thanks @ast0815!

**Comment by brichards64** [comment]
looks like all your PRs contain all the changes from the previous, so ill wait for the bonsai question on #71 PR first as this contains all that ones changes.

**Comment by ast0815** [comment]
I would say, yes. I hope that the weights are somewhat universal (= do not depend on the supernova model). Someone should check that though. It might also be a good idea to re-generate them when changing the energy reconstruction code.

**Comment by tdealtry** [comment]
Regenerate? Yes, we should have the option to do this!!! So it'd be great if you could commit your relevant macros including documentation on the process. I don't know where exactly - a new repo? A new `tuning` folder here?

**Pull request merged**
