### PR TITLE
Use SubSamples for Recon

### PR DESCRIPTION
**Pull request by tdealtry**
Instead of using `WCSimRootEvent`, use `SubSample`

This is an evolution of #62

### CODE REVIEW

**Comment by ast0815** [comment]
It is not working:

```
[3]: DEBUG: Preparing 1 ID samples
[4]: DEBUG: Sorting sample
[3]: DEBUG: Preparing 0 OD samples
[3]:  qqq Number of data samples 1
[3]: DEBUG: NHits::AlgNDigits(). Number of entries in input digit collection: 850
[2]: INFO: Found 1 NDigit trigger(s) from ID
[1]: [3] DEBUG: Trigger times after sorting:
[1]: [3] DEBUG: Trigger: 0      Readout windows: 1.67641e+10 ns 1.67641e+10 ns  Mask windows: 1.67641e+10 ns    1.67641e+10 ns
[2]: INFO: Have 1 triggers to save times:
[2]: INFO:      [1.67641e+10 ns, 1.67641e+10 ns] 1.67641e+10 ns ns with type NDigits extra info 59
[3]: DEBUG: Total time shift is 0 ns
[1]: TODO after WCSim/WCSim#286 is merged, uncomment SetPhotonIds
[3]: DEBUG: Trigger 0 has 0 hits
[2]: INFO: 0 hits in current trigger. Not running BONSAI
[3]: DEBUG: Saving the result of 0 reconstructions
```

It seems like both the extra info (59) and the lack of hits in the trigger are unviversal for a all events.

**Comment by ast0815** [comment]
Now it works. 👍

**Comment by brichards64** [comment]
ahh some conflicts from other PRs can you fix them

**Comment by tdealtry** [comment]
Ready to go

**Pull request merged**
