### PR TITLE
FLOWER

### PR DESCRIPTION
**Pull request by tdealtry**
energetic-bonsai is renaming, so this
- Uses the new class, library, etc. names
- Renames the Tool to FLOWERRecon

Evolution of #50 (mainly because there were some Setup.sh changes already there)

### CODE REVIEW

**Comment by tdealtry** [comment]
This is ready for review now the FLOWER PR is merged, the repo is renamed, etc

**Comment by brichards64** [comment]
not sure if you want the optional cuda line in the readme otherwise i would have resolved the conflict myself.

can you put it to what you like it then ill merge

**Comment by tdealtry** [comment]
Ready to go

**Comment by brichards64** [comment]
urgh your other pr made some bonsai conflicts

**Comment by tdealtry** [comment]
Ready to go again!

**Pull request merged**
