### PR TITLE
Add WCSimReader and DataOut tools

### PR DESCRIPTION
**Pull request by tdealtry**
This kind of follows on from #2, but there have been some changes to WCSimReader for pass through information. Closing #2 so the code that actually works is reviewed

The WCSimReader tool takes WCSim files and formats the data (predominantly digits and PMT positions) to store in the transient data model. 
Makefile was modified to add the WCSim and ROOT libs/includes
What's not implemented:
* Chopping the WCSim events into specific time slices. This requires HK software group discussion as dark noise makes this non-trivial.

The DataOut tool creates a WCSim-like output file with some changes:
* Remove digits that aren't in the trigger window(s)
* Extra variables to link from this file to the original WCSim files & event numbers

Probably the only thing not implemented that exists in WCSim is a flag to state whether multiple digits are allowed per PMT per trigger window.

WCSimReaderTest is a toolchain to test these two tools

For Travis to pass checks, WCSim & ROOT need to be used. https://github.com/tdealtry/WCSim/tree/trigger should be the version of WCSim used, as this contains some unmerged WCSim PRs that are required for these tools

### CODE REVIEW

**Comment by brichards64** [comment]
Hi Tom, I edited your makefile changes.

The idea with the makefile is that you should never have to change the make lines only the dependencies at the top. so ass root and wcsim are dependencies for the data model rather than adding them to every make line i just reference them in the data model include and lib

**Comment by brichards64** [comment]
Hi Tom can you also update the Setup.sh in your PR to say the following

```
#!/bin/bash

#Application path location of applicaiton

ToolDAQapp=`pwd`

source /root/HyperK/root/bin/thisroot.sh 

export LD_LIBRARY_PATH=${ToolDAQapp}/lib:${ToolDAQapp}/ToolDAQ/zeromq-4.0.7/lib:${ToolDAQapp}/ToolDAQ/boost_1_66_0/install/lib:/root/HyperK/root/lib:/root/HyperK/WCSim:$LD_LIBRARY_PATH
```

**Comment by tdealtry** [comment]
Thanks Ben. I just pushed the commit.

Just a thought - not all people will be using docker, so something along the lines of `$ROOTSYS/lib:$WCSIMDIR` instead of `/root/HyperK/root/lib:/root/HyperK/WCSim`
would be better. But I'm not sure if your docker sets the $WCSIMDIR variable so didn't do this.

**Comment by brichards64** [comment]
Hi Tom,

I agree. Might be worth having a phone call today if your free. Im going to try and get this up and running this morning so the above was just a temp fix that we can correct in a bit.

Also im going to try and set you up an account here at QMUL today on the test stand so you can have docker and a GPU.

thanks

Ben

**Comment by brichards64** [comment]
That works for me, so 3:30pm

I think i have your skype so we can chat there.

thanks

Ben

**Comment by brichards64** [comment]
Hi Tom,

If you can merge in the latest change iv just made into your branch i think we might finally get a green light on travis.

thanks

Ben

**Comment by brichards64** [comment]
Still red,  i know what the issue is and it should be easier to solve after i merge it so ill just go ahead and do that.

thanks Tom

**Pull request merged**
